name: ci-cd Deploy

on:
  push:
    branches:
      - main
  pull_request: 

permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: Build e Teste da Aplicação
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependencias
        run: npm ci
        
      - name: Rodar testes
        run: npm test 
      
      - name: Build
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v6

      - name: Fazer upload do artefato do Pages
        uses: actions/upload-pages-artifact@v5
        with:
          path: './dist'

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5